### ISSUE TITLE
'ClipVisionModel' object has no attribute 'processor'

### ISSUE THREAD

**Issue by MoonMoon82** [laksjdjf/IPAdapter-ComfyUI#42]
After the latest update of ComfyUI I get this error message while running the "Apply IPAdapter" node:

```
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "e:\Stablediffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 159, in adapter
    cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 228, in clip_vision_encode
    inputs = clip_vision.processor(images=img, return_tensors="pt")
AttributeError: 'ClipVisionModel' object has no attribute 'processor'
```

Could you please check?

**Comment by Jasonlin00** [comment]
i got the same error.

**Comment by MoonMoon82** [comment]
IP Adapter Plus already fixed this issue in their nodes:
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/48

**Comment by cerarslan** [comment]
> IP Adapter Plus already fixed this issue in their nodes: [cubiq/ComfyUI_IPAdapter_plus#48](https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/48)

same for me

**Comment by Losswife** [comment]
I am still getting this error. I have installed every new IPAdapter model within Comfy Manager. I'm out of ideas.

**Comment by imesha10** [comment]
I'm getting this error too. I'm using comfyui on runpod.io.
When I loaded it up just now for some reason I've got that error.

```
Error occurred when executing IPAdapter:

'ClipVisionModel' object has no attribute 'processor'

File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 138, in adapter
cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
File "/workspace/ComfyUI/custom_nodes/IPAdapter-ComfyUI/ip_adapter.py", line 205, in clip_vision_encode
inputs = clip_vision.processor(images=img, return_tensors="pt")
```

**Comment by solaresmty** [comment]
I am trying to use AloeVera's in ComfyUI but I get this error and I don't know much about the subject but I would like some guidance on what I have to do to make it work. thank you

Error occurred when executing IPAdapter:

'ClipVisionModel' object has no attribute 'processor'

File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 138, in adapter
cond, uncond, outputs = self.clip_vision_encode(clip_vision, image, self.plus)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 205, in clip_vision_encode
inputs = clip_vision.processor(images=img, return_tensors="pt")
^^^^^^^^^^^^^^^^^^^^^

**Comment by ttchina** [comment]
same here, so i can only use another node called "apply ipadapter" to make it work

**Comment by solaresmty** [comment]
> same here, so i can only use another node called "apply ipadapter" to make it work

where did you download it from? to try to use that

**Comment by doctorbinsibar** [comment]
this wont work. It using useless amounts of vram. I tried on V100 with 12gb still same error.  Now on 30 GB VRam its working fine !

**Comment by cerarslan** [comment]
> > same here, so i can only use another node called "apply ipadapter" to make it work
> 
> where did you download it from? to try to use that

Try ip-adapter plus extension it is in there.

**Comment by laksjdjf** [comment]
i fixed it.

**Comment by Manish-cel** [comment]
> i fixed it.

please share how to fix this issue.

**Comment by cubiq** [comment]
I still think we should merge :smile:

**Comment by s1702w0246** [comment]
> i fixed it.

need update ,thanks

**Comment by TitusHora** [comment]
I updated everything (comfyui + all the plugins) and I am still getting this error message: 'ClipVisionModel' object has no attribute 'processor'.

Can anybody, please, help me fix this? Thank you!

**Comment by cubiq** [comment]
> 
> Can anybody, please, help me fix this? Thank you!

you need to download the latest version, updating might not be enough

**Comment by TitusHora** [comment]
Thank you, cubiq; I did download ip adapter plus. safetensors and it works now.

**Comment by TitusHora** [comment]
> > Can anybody, please, help me fix this? Thank you!
> 
> you need to download the latest version, updating might not be enough

Thank you, @cubiq; I did download ip adapter plus. safetensors and it works now.
